name: Unit Tests On PR

on:
  pull_request_target:

jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
      - name: Approve
        run: echo For security reasons, all pull requests need to be approved first before running any automated CI.

  tests:
    name: Unit tests

    runs-on: ubuntu-latest

    needs: [approve]

    environment: test-env

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate typechain files from abi
        run: yarn generate-types

      - name: Run tests
        env:
          MAINNET_PROVIDER_URL: ${{ secrets.MAINNET_PROVIDER_URL }}
        run: yarn test
