name: Unit Tests

on:
  push:
  pull_request_target:

jobs:
  tests:
    name: Unit tests

    runs-on: ubuntu-latest

    environment: test-env

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate typechain files from abi
        run: yarn generate-types

      - name: Run tests
        env:
          MAINNET_PROVIDER_URL: ${{ secrets.MAINNET_PROVIDER_URL }}
        run: yarn test
